_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
aa:
    value: rand-m9-mstd0.5-inc1
auto_resume:
    value: true
batch_size:
    value: 256
blocksize:
    value: 1
clip_grad:
    value: null
color_jitter:
    value: 0.4
crop_pct:
    value: null
cutmix:
    value: 1
cutmix_minmax:
    value: null
cutoff_epoch:
    value: 0
data_path:
    value: /media/shahanahmed/b8c6fb5d-b937-4730-bb0f-ac0eba675d7e/DATASET/cifat100
data_set:
    value: IMNET
device:
    value: cuda
disable_eval:
    value: false
dist_eval:
    value: true
dist_on_itp:
    value: false
dist_url:
    value: env://
distributed:
    value: false
drop_mode:
    value: standard
drop_path:
    value: 0
drop_schedule:
    value: constant
dropout:
    value: 0
enable_wandb:
    value: false
epochs:
    value: 5
eval:
    value: false
eval_data_path:
    value: null
finetune:
    value: ""
head_init_scale:
    value: 1
imagenet_default_mean_and_std:
    value: true
input_size:
    value: 32
layer_decay:
    value: 1
layer_scale_init_value:
    value: 1e-06
local_rank:
    value: -1
log_dir:
    value: null
lr:
    value: 0.004
min_lr:
    value: 1e-06
mixup:
    value: 0.8
mixup_mode:
    value: batch
mixup_prob:
    value: 1
mixup_switch_prob:
    value: 0.5
model:
    value: convnext_tiny
model_ema:
    value: false
model_ema_decay:
    value: 0.9999
model_ema_eval:
    value: false
model_ema_force_cpu:
    value: false
model_key:
    value: model|module
model_prefix:
    value: ""
momentum:
    value: 0.9
nb_classes:
    value: 1000
nsamples:
    value: 4096
num_workers:
    value: 10
opt:
    value: adamw
opt_betas:
    value: null
opt_eps:
    value: 1e-08
output_dir:
    value: ""
pin_mem:
    value: true
project:
    value: convnext
prune_granularity:
    value: null
prune_metric:
    value: null
recount:
    value: 1
remode:
    value: pixel
reprob:
    value: 0.25
resplit:
    value: false
save_ckpt:
    value: true
save_ckpt_freq:
    value: 1
save_ckpt_num:
    value: 3
seed:
    value: 0
smoothing:
    value: 0.1
sparsity:
    value: 0
start_epoch:
    value: 0
train_interpolation:
    value: bicubic
update_freq:
    value: 1
use_amp:
    value: false
wandb_ckpt:
    value: false
warmup_epochs:
    value: 50
warmup_steps:
    value: -1
weight_decay:
    value: 0.05
weight_decay_end:
    value: null
world_size:
    value: 1
